// GENERATED by scripts/us-pages-register.mjs — do not edit by hand.
// North American guides about pests BuzzSkito does not treat. The phone "Get a free quote"
// bar is hidden on them, for the same reason it is hidden on the older adjacent-pest pages
// (lib/adjacent-pest-routes.ts): the page itself says we do not offer that service.
// These pages are rendered by components/GuidePage.tsx, so the grep that regenerates
// adjacent-pest-routes.ts cannot see them. That is why they live in their own file.
export const US_GUIDE_ADJACENT_ROUTES = new Set<string>([
  "/learn/bed-bugs",
  "/blog/what-do-bed-bugs-look-like",
  "/blog/where-do-bed-bugs-hide",
  "/blog/how-to-get-rid-of-bed-bugs",
  "/blog/sugar-ants",
  "/blog/vamoose-for-mice",
  "/blog/mice-exterminator",
  "/learn/cockroaches",
  "/blog/german-cockroaches",
  "/blog/commercial-pest-control",
])
