/**
 * BuzzSkito — Google Indexing API submission script
 *
 * Runs automatically after `npm run build` via the "postbuild" script.
 *
 * SETUP (one-time):
 * 1. Go to Google Search Console → Settings → Ownership verification → API access
 * 2. Create a Service Account in Google Cloud Console with "Indexing API" enabled
 * 3. Download the JSON key and save it as `scripts/google-service-account.json`
 *    (this file is .gitignored — never commit it)
 * 4. In Search Console, add the service account email as a "Full User" owner
 * 5. npm install google-auth-library   (run once)
 *
 * The script skips gracefully if the key file is missing so dev builds still work.
 */

import { readFileSync, existsSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const KEY_PATH = resolve(__dirname, 'google-service-account.json')
const SITE_URL = 'https://buzzskito.ca'

// All canonical URLs — keep in sync with app/sitemap.ts
const URLS = [
  // ── US-GUIDES:START (generated by scripts/us-pages-register.mjs — do not edit by hand) ──
  // North American pest guides (Oct 2026): hubs, product hubs, guides by search demand, then the broadened guides
  `${SITE_URL}/learn/bed-bugs`,
  `${SITE_URL}/learn/ants`,
  `${SITE_URL}/learn/mice`,
  `${SITE_URL}/learn/cockroaches`,
  `${SITE_URL}/pest-product-guides/ant-control`,
  `${SITE_URL}/pest-product-guides/cockroach-control`,
  `${SITE_URL}/blog/how-to-get-rid-of-bed-bugs`,
  `${SITE_URL}/blog/what-do-bed-bugs-look-like`,
  `${SITE_URL}/blog/sugar-ants`,
  `${SITE_URL}/blog/commercial-pest-control`,
  `${SITE_URL}/blog/mice-exterminator`,
  `${SITE_URL}/blog/seed-ticks`,
  `${SITE_URL}/blog/flying-ants`,
  `${SITE_URL}/blog/deer-mice`,
  `${SITE_URL}/blog/do-cockroaches-bite`,
  `${SITE_URL}/blog/can-cockroaches-fly`,
  `${SITE_URL}/blog/borax-for-ants`,
  `${SITE_URL}/blog/how-to-get-rid-of-ants-in-the-house`,
  `${SITE_URL}/blog/what-do-ants-eat`,
  `${SITE_URL}/blog/how-to-get-rid-of-mosquitoes`,
  `${SITE_URL}/blog/german-cockroaches`,
  `${SITE_URL}/blog/steel-wool-for-mice`,
  `${SITE_URL}/blog/flying-ants-vs-termites`,
  `${SITE_URL}/blog/what-do-mice-eat`,
  `${SITE_URL}/blog/how-long-do-ants-live`,
  `${SITE_URL}/blog/how-to-keep-mosquitoes-away`,
  `${SITE_URL}/blog/peppermint-oil-for-mice`,
  `${SITE_URL}/blog/ghost-ants`,
  `${SITE_URL}/blog/what-kills-ticks-on-dogs-instantly`,
  `${SITE_URL}/blog/bugs-that-look-like-cockroaches`,
  `${SITE_URL}/blog/bugs-that-look-like-bed-bugs`,
  `${SITE_URL}/blog/what-do-ticks-look-like`,
  `${SITE_URL}/blog/vamoose-for-mice`,
  `${SITE_URL}/blog/mice-removal`,
  `${SITE_URL}/blog/lawn-pest-control`,
  `${SITE_URL}/blog/mice-traps`,
  `${SITE_URL}/blog/army-ants`,
  `${SITE_URL}/blog/mice-repellent`,
  `${SITE_URL}/blog/can-mice-climb-walls`,
  `${SITE_URL}/blog/are-mice-nocturnal`,
  `${SITE_URL}/blog/do-mosquitoes-bite-dogs`,
  `${SITE_URL}/blog/field-mice`,
  `${SITE_URL}/blog/ticks-in-michigan`,
  `${SITE_URL}/blog/tiny-ants`,
  `${SITE_URL}/blog/do-carpenter-ants-bite`,
  `${SITE_URL}/blog/types-of-mice`,
  `${SITE_URL}/blog/do-mothballs-keep-mice-away`,
  `${SITE_URL}/blog/how-to-get-rid-of-ants-in-the-kitchen`,
  `${SITE_URL}/blog/are-mosquitoes-attracted-to-light`,
  `${SITE_URL}/blog/what-smells-do-mice-hate`,
  `${SITE_URL}/blog/ticks-on-dogs`,
  `${SITE_URL}/blog/diy-pest-control`,
  `${SITE_URL}/blog/how-much-is-pest-control`,
  `${SITE_URL}/blog/do-ants-bite`,
  `${SITE_URL}/blog/black-bed-bugs`,
  `${SITE_URL}/blog/where-do-bed-bugs-hide`,
  `${SITE_URL}/blog/red-ants`,
  `${SITE_URL}/blog/does-vinegar-kill-ants`,
  `${SITE_URL}/blog/alaska-mosquitoes`,
  `${SITE_URL}/blog/how-to-get-rid-of-mice-humanely`,
  `${SITE_URL}/blog/what-kills-ticks`,
  `${SITE_URL}/blog/bullet-ants`,
  `${SITE_URL}/blog/baby-mice`,
  `${SITE_URL}/blog/does-lysol-kill-bed-bugs`,
  `${SITE_URL}/blog/does-alcohol-kill-bed-bugs`,
  `${SITE_URL}/blog/ticks-that-carry-lyme-disease`,
  `${SITE_URL}/blog/what-do-baby-cockroaches-look-like`,
  `${SITE_URL}/blog/do-chickens-eat-ticks`,
  `${SITE_URL}/blog/bed-bugs-on-mattress`,
  `${SITE_URL}/blog/where-do-cockroaches-come-from`,
  `${SITE_URL}/blog/how-to-get-rid-of-mice-canada`,
  `${SITE_URL}/blog/how-to-get-rid-of-ants-canada`,
  `${SITE_URL}/blog/how-to-get-rid-of-cockroaches-canada`,
  `${SITE_URL}/blog/carpenter-ants-canada`,
  `${SITE_URL}/blog/mosquito-repellent-plants-ontario`,
  `${SITE_URL}/blog/what-kills-bed-bugs-instantly-canada`,
  `${SITE_URL}/blog/what-does-mouse-poop-look-like-canada`,
  `${SITE_URL}/blog/bed-bug-spray-canada`,
  `${SITE_URL}/blog/where-do-mosquitoes-go-in-winter-ontario`,
  // ── US-GUIDES:END ──
  // Core pages
  `${SITE_URL}/`,
  `${SITE_URL}/mosquito-control`,
  `${SITE_URL}/tick-control`,
  `${SITE_URL}/service-areas`,
  `${SITE_URL}/contact`,
  `${SITE_URL}/buzzskito-history`,
  `${SITE_URL}/frequently-asked-question`,
  `${SITE_URL}/blog`,

  // Mosquito city pages
  `${SITE_URL}/mosquito-control-sauga`,
  `${SITE_URL}/toronto-mosquito-control`,
  `${SITE_URL}/brampton-mosquito-control`,
  `${SITE_URL}/oakville-mosquito-control`,
  `${SITE_URL}/burlington-mosquito-spray`,
  `${SITE_URL}/hamilton-mosquito-control`,
  `${SITE_URL}/vaughan-mosquito-control`,
  `${SITE_URL}/richmond-hill-mosquito-control`,
  `${SITE_URL}/markham-mosquito-control`,
  `${SITE_URL}/etobicoke-mosquito-control`,
  `${SITE_URL}/scarborough-mosquito-control`,
  `${SITE_URL}/north-york-mosquito-control`,
  `${SITE_URL}/caledon-mosquito-control`,
  `${SITE_URL}/milton-mosquito-control`,
  `${SITE_URL}/georgetown-mosquito-control`,
  `${SITE_URL}/halton-hills-mosquito-control`,
  `${SITE_URL}/king-city-mosquito-control`,
  `${SITE_URL}/woodbridge-mosquito-control`,
  `${SITE_URL}/thornhill-mosquito-control`,

  // Tick city pages
  `${SITE_URL}/mississauga-tick-spray`,
  `${SITE_URL}/toronto-tick-spray-1`,
  `${SITE_URL}/brampton-tick-spray-1`,
  `${SITE_URL}/oakville-tick-spray-1`,
  `${SITE_URL}/burlington-tick-spray`,
  `${SITE_URL}/hamilton-tick-spray-1`,
  `${SITE_URL}/vaughan-tick-spray`,
  `${SITE_URL}/richmond-hill-tick-spray`,
  `${SITE_URL}/markham-tick-spray`,
  `${SITE_URL}/etobicoke-tick-spray`,
  `${SITE_URL}/scarborough-tick-spray`,
  `${SITE_URL}/north-york-tick-spray`,
  `${SITE_URL}/caledon-tick-spray`,
  `${SITE_URL}/milton-tick-spray`,
  `${SITE_URL}/georgetown-tick-spray`,
  `${SITE_URL}/halton-hills-tick-spray`,
  `${SITE_URL}/king-city-tick-spray`,
  `${SITE_URL}/woodbridge-tick-spray`,
  `${SITE_URL}/thornhill-tick-spray`,

  // Mosquito blogs
  `${SITE_URL}/blog/ultimate-backyard-mosquito-control-guide`,
  `${SITE_URL}/blog/mosquito-season-gta-when-does-it-start`,
  `${SITE_URL}/blog/how-long-does-mosquito-spray-last`,
  `${SITE_URL}/blog/mosquito-vs-diy-vs-professional-control`,
  `${SITE_URL}/blog/west-nile-virus-mosquito-risk-ontario`,
  `${SITE_URL}/blog/how-to-prevent-mosquitoes-in-your-backyard`,

  // Tick blogs
  `${SITE_URL}/blog/ultimate-tick-control-guide-ontario`,
  `${SITE_URL}/blog/lyme-disease-tick-prevention-ontario`,
  `${SITE_URL}/blog/what-ticks-look-like-ontario`,
  `${SITE_URL}/blog/how-to-remove-tick-safely`,
  `${SITE_URL}/blog/best-tick-control-yard-treatment`,
  `${SITE_URL}/blog/tick-season-ontario-when-are-ticks-active`,

  // City-targeting blogs
  `${SITE_URL}/blog/mosquito-control-vaughan-york-region`,
  `${SITE_URL}/blog/tick-control-richmond-hill-markham`,
  `${SITE_URL}/blog/mosquito-control-etobicoke-north-york`,
  `${SITE_URL}/blog/mosquito-season-scarborough-east-toronto`,
  `${SITE_URL}/blog/tick-prevention-caledon-halton-hills`,
  `${SITE_URL}/blog/mosquito-control-milton-georgetown`,
  `${SITE_URL}/blog/is-mosquito-spray-safe-kids-pets`,
  `${SITE_URL}/blog/how-to-choose-mosquito-control-company-gta`,
  `${SITE_URL}/blog/mosquito-control-near-water-ravines-gta`,
  `${SITE_URL}/blog/when-to-schedule-first-mosquito-treatment-ontario`,
]

async function submitUrls() {
  if (!existsSync(KEY_PATH)) {
    console.log('ℹ️  Google Indexing API: service account key not found — skipping.')
    console.log('   Add scripts/google-service-account.json to enable auto-indexing.')
    return
  }

  // Dynamically import so the script doesn't hard-fail without google-auth-library
  let GoogleAuth
  try {
    const mod = await import('google-auth-library')
    GoogleAuth = mod.GoogleAuth
  } catch {
    console.log('ℹ️  google-auth-library not installed — skipping indexing API.')
    console.log('   Run: npm install google-auth-library')
    return
  }

  const keyFile = JSON.parse(readFileSync(KEY_PATH, 'utf-8'))
  const auth = new GoogleAuth({
    credentials: keyFile,
    scopes: ['https://www.googleapis.com/auth/indexing'],
  })

  const client = await auth.getClient()
  const endpoint = 'https://indexing.googleapis.com/v3/urlNotifications:publish'

  console.log(`\n🚀 Submitting ${URLS.length} URLs to Google Indexing API...\n`)

  let success = 0
  let failed = 0

  for (const url of URLS) {
    try {
      const res = await client.request({
        url: endpoint,
        method: 'POST',
        data: { url, type: 'URL_UPDATED' },
      })
      if (res.status === 200) {
        console.log(`  ✅ ${url}`)
        success++
      } else {
        console.log(`  ⚠️  ${url} — status ${res.status}`)
        failed++
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err)
      console.log(`  ❌ ${url} — ${msg}`)
      failed++
    }

    // Respect API rate limit: 200 requests/day, pace at ~1/sec
    await new Promise((r) => setTimeout(r, 500))
  }

  console.log(`\n✅ Done — ${success} submitted, ${failed} failed.\n`)
}

submitUrls()
