import { readFileSync } from 'fs'
const d = JSON.parse(readFileSync('gsc_full_scan.json','utf-8'))
const rd = f => readFileSync(f,'utf-8').trim().split('\n').map(l=>l.replace('app/blog/','').trim()).filter(Boolean)
const noaward = new Set(rd('_noaward.txt')), hasaward = new Set(rd('_hasaward.txt'))
const p = u => u.replace(/^https?:\/\/buzzskito\.ca/,'')
const grab = (set) => d.pages.filter(r=>{const m=p(r.page).match(/^\/blog\/(.+?)\/?$/); return m && set.has(m[1])})
  .map(r=>({slug:p(r.page).replace('/blog/','').replace(/\/$/,''), clicks:r.clicks, impr:r.impressions}))
  .sort((a,b)=>b.clicks-a.clicks)
const A = grab(noaward), B = grab(hasaward)
const S = a=>a.reduce((s,r)=>s+r.clicks,0)

console.log('='.repeat(84))
console.log('AWARDROW COVERAGE, WEIGHTED BY REAL TRAFFIC')
console.log('='.repeat(84))
console.log(`  WITH    AwardRow : ${String(B.length).padStart(3)} pages  ${S(B).toLocaleString().padStart(6)} clicks/mo`)
console.log(`  WITHOUT AwardRow : ${String(A.length).padStart(3)} pages  ${S(A).toLocaleString().padStart(6)} clicks/mo`)
console.log(`  => ${(S(A)/(S(A)+S(B))*100).toFixed(0)}% of affiliate traffic lands on a page without the better format\n`)

console.log('  TOP NO-AWARDROW PAGES BY TRAFFIC:')
for (const r of A.slice(0,22))
  console.log(`    ${String(r.clicks).padStart(5)} clk  ${String(r.impr).padStart(7)} impr  ${r.slug}`)
const t = A.slice(0,22).reduce((s,r)=>s+r.clicks,0)
console.log(`\n  those 22 carry ${t.toLocaleString()} clicks/mo (${(t/S(A)*100).toFixed(0)}% of the gap)`)
console.log('\n' + '='.repeat(84))
console.log('WHAT FIXING THEM IS WORTH')
console.log('='.repeat(84))
console.log('  Measured on this site: AwardRow click-out 23.3% vs TopPick 10.2%.')
console.log('  Amazon click is worth $0.221 (9.48% conv x $46.53 AOV x ~5% commission).')
for (const [label, pp] of [['conservative +5pp click-out',0.05],['midpoint +8pp',0.08],['measured gap +13pp',0.13]])
  console.log(`    ${label.padEnd(30)} +$${(t*pp*0.221).toFixed(0).padStart(4)}/month`)
console.log('\n  This needs NO new traffic and NO ranking change. It is the only lever')
console.log('  on the list with a measured effect size from this site\'s own data.')
